name: verify
on: [push, pull_request]
jobs:
  maven-verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up Workspace Enviroment Variable
        run: echo "WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV        
      - name: Build with Maven  within a virtual X Server Environment
        run: xvfb-run mvn clean verify checkstyle:check pmd:check pmd:cpd-check findbugs:check -f ./ddk-parent/pom.xml --batch-mode --fail-at-end
      - name: Archive Tycho Surefire Plugin
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: tycho-surefire-plugin
          path: ${{ env.GITHUB_WORKSPACE }}/dsl-devkit/com.avaloq.tools.ddk.xtext.test/target/work/data/.metadata/.log
